/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnidemo_JniUtils */

#ifndef _Included_com_jnidemo_JniUtils
#define _Included_com_jnidemo_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnidemo_JniUtils
 * Method:    getSignature
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jnidemo_JniUtils_getSignature
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jnidemo_JniUtils
 * Method:    getPackname
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jnidemo_JniUtils_getPackname
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
